version: "3.9"

services:
  backend_test_911:
    container_name: backend_test_911
    build:
      context: .
      dockerfile: docker/Dockerfile.back
    env_file: .env
    restart: always
    command: >
      sh -c "
            daphne -b 0.0.0.0 -p 8888 config.asgi:application && 
            python manage.py fill_data
            "
    depends_on:
      database_test_911:
        condition: service_started
    networks:
      - app_network_test
    volumes:
      - .:/911
    ports:
      - "8888:8888"

  redis_test_911:
    image: redis:7.0.5-alpine
    container_name: redis_test_911
    hostname: redis
    networks:
      - app_network_test
    env_file: .env
    restart: always

  database_test_911:
    container_name: postgres_test_911
    image: postgres:16.2-alpine
    restart: unless-stopped
    env_file: .env
    networks:
      - app_network_test
    volumes:
      - postgres_test_911:/var/lib/postgresql/data/

  elastic_node:
    image: elasticsearch:8.14.0
    container_name: elastic_node
    environment:
      - discovery.type=single-node
      - node.name=odfe-node
      - cluster.name=es-vasya-cluster
      - discovery.seed_hosts=odfe-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: always
    depends_on:
      - nginx_test
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "1000m"
    #     max-file: "10"
    #    ports:
    #      - "9200:9200"
    networks:
      - app_network_test

  #  kibana:
  #    container_name: kibana
  #    image: kibana:7.17.9
  #    restart: always
  #    environment:
  #      - node.name=kib7
  #      - cluster.name=es-vasya-cluster
  #      - ELASTICSEARCH_HOSTS=http://elastic_node:9200
  #    volumes:
  #      - ./kibana.yml:/opt/kibana/config/kibana.yml
  #    ports:
  #      - "5601:5601"
  #    depends_on:
  #      - elastic_node
  #    networks:
  #      - app_network_test

  nginx_test:
    container_name: nginx_test_911
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile.nginx
    env_file: .env
    ports:
      - "8080:8080"
      - "8882:8882"
      - "8881:8881"
    volumes_from:
      - backend_test_911
    volumes:
      - static:/static/
    restart: always
    networks:
      - app_network_test
    links:
      - backend_test_911
    depends_on:
      - backend_test_911
      - database_test_911

  worker_test:
    build:
      context: .
      dockerfile: docker/Dockerfile.back
    hostname: worker_test
    entrypoint: celery
    env_file: .env
    command: -A config.celery.app worker --loglevel=info --concurrency 1 -E
    volumes_from:
      - backend_test_911
    networks:
      - app_network_test
    links:
      - redis_test_911
    depends_on:
      - redis_test_911
    restart: always

  beat_test:
    build:
      context: .
      dockerfile: docker/Dockerfile.back
    hostname: worker_beat
    entrypoint: celery
    env_file: .env
    command: -A config.celery.app beat -l info -S django
    volumes:
      - .:/911
    volumes_from:
      - backend_test_911
    networks:
      - app_network_test
    links:
      - redis_test_911
    depends_on:
      - redis_test_911
    restart: always

volumes:
  postgres_test_911:
  elasticsearch_data:
  static:

networks:
  app_network_test:
