[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "website_project.settings.dev"
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short --strict-markers"
testpaths = ["website_api/tests"]

