# Generated by Django 5.0.3 on 2024-11-14 16:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "admin_status",
                    models.CharField(
                        choices=[("active", "Активен"), ("blocked", "Заблокирован")],
                        default="active",
                        max_length=25,
                        verbose_name="Статус админа",
                    ),
                ),
                (
                    "user_login",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Логин админа"
                    ),
                ),
            ],
            options={
                "verbose_name": "Администратор",
                "verbose_name_plural": "Администраторы",
                "db_table": "admin_db",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название города"),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
                "db_table": "city_db",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "client_status",
                    models.CharField(
                        choices=[("active", "Активен"), ("blocked", "Заблокирован")],
                        default="active",
                        verbose_name="Статус клиента",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "db_table": "client_db",
            },
        ),
        migrations.CreateModel(
            name="CommissionPercent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Процент комиссии",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=50, verbose_name="Номер телефона"),
                ),
                (
                    "whatsapp_partner",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL WhatsApp партнера"
                    ),
                ),
                ("telegram", models.URLField(verbose_name="URL Telegram")),
                (
                    "whatsapp_client",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL WhatsApp клиента"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакты",
                "verbose_name_plural": "Контакты",
                "db_table": "contacts_db",
            },
        ),
        migrations.CreateModel(
            name="DepositMinimum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Минимальный депозит",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Название опции"
                    ),
                ),
            ],
            options={
                "verbose_name": "Опция",
                "verbose_name_plural": "Опции",
                "db_table": "option_db",
            },
        ),
        migrations.CreateModel(
            name="OrderConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("radius", "Радиус колеса"),
                            ("fuel_type", "Тип топлива"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Условия заказа",
                "verbose_name_plural": "Условия заказа",
                "db_table": "order_condition_db",
            },
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="Вопрос")),
                ("answer", models.TextField(verbose_name="Ответ")),
                (
                    "questioner",
                    models.CharField(
                        choices=[("partner", "Партнер"), ("client", "Клиент")],
                        verbose_name="Тип спрашивающего",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопросы и ответы",
                "verbose_name_plural": "Вопросы и ответы",
                "db_table": "question_answer_db",
            },
        ),
        migrations.CreateModel(
            name="Rules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rules", models.TextField(verbose_name="Правила пользования")),
            ],
            options={
                "verbose_name": "Правила пользования",
                "verbose_name_plural": "Правила пользования",
                "db_table": "rules_db",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Название услуги"
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "db_table": "service_db",
            },
        ),
        migrations.CreateModel(
            name="TechnicCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
            ],
            options={
                "verbose_name": "Категория автомобиля",
                "verbose_name_plural": "Категории автомобилей",
                "db_table": "technic_category_db",
            },
        ),
        migrations.CreateModel(
            name="OptionPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="src.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="src.option",
                        verbose_name="Опция",
                    ),
                ),
                (
                    "technic_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="src.techniccategory",
                        verbose_name="Категория техники",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цена опции",
                "verbose_name_plural": "Цена опции",
                "db_table": "option_price_db",
            },
        ),
        migrations.AddField(
            model_name="option",
            name="cities",
            field=models.ManyToManyField(
                related_name="options",
                through="src.OptionPrice",
                to="src.city",
                verbose_name="Город",
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point_coordinates", models.JSONField(default=list)),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Комментарий к заказу",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Итоговая цена",
                    ),
                ),
                (
                    "options_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Цена опций",
                    ),
                ),
                (
                    "delivery_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Цена опций",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Создан"),
                            ("on_the_way", "В пути"),
                            ("in_progress", "В процессе выполнения"),
                            ("on_confirmation", "На подтверждении"),
                            ("done", "Выполнен"),
                            ("cancelled", "Отменен"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=50,
                        verbose_name="Статус заказа",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата, время создания заказа"
                    ),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата, время обновления заказа"
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="Условия заказа",
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Комиссия, которую заплатит партнер",
                    ),
                ),
                (
                    "technic_brand_model",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Техника клиента",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="src.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="src.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "db_table": "order_db",
            },
        ),
        migrations.CreateModel(
            name="OrderOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="src.option",
                        verbose_name="Опция",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="src.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ с опцией",
                "verbose_name_plural": "Заказы с опциями",
                "db_table": "order_option_db",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="options",
            field=models.ManyToManyField(
                related_name="orders",
                through="src.OrderOption",
                to="src.option",
                verbose_name="Опции",
            ),
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=60, verbose_name="Фамилия")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=4,
                        verbose_name="Рейтинг партнера",
                    ),
                ),
                (
                    "date_confirmed",
                    models.DateField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата подтверждения партнера",
                    ),
                ),
                (
                    "legal_status",
                    models.CharField(
                        choices=[
                            ("legal_entity", "Юридическое лицо"),
                            ("individual", "Физическое лицо"),
                        ],
                        verbose_name="Юридический статус партнера",
                    ),
                ),
                (
                    "is_working",
                    models.BooleanField(
                        default=False, verbose_name="В процессе работы"
                    ),
                ),
                (
                    "last_shift_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Время последнего захода на смену",
                    ),
                ),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/partners/2024-11-14 19:08:02",
                        verbose_name="Фото партнера",
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Доход партнера",
                    ),
                ),
                (
                    "verify",
                    models.CharField(
                        choices=[
                            ("on_confirmation", "Ожидает"),
                            ("confirmed", "Подтвержден"),
                            ("rejected", "Отклонен"),
                            ("blocked", "Заблокирован"),
                        ],
                        default="on_confirmation",
                        max_length=50,
                        verbose_name="Верификация партнера",
                    ),
                ),
                (
                    "commission_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Комиссионный баланс",
                    ),
                ),
                (
                    "deposit_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Депозитный баланс",
                    ),
                ),
                (
                    "deposit_balance_history",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="История баланса"
                    ),
                ),
                (
                    "commission_balance_history",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="История баланса"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partners",
                        to="src.city",
                        verbose_name="Город работы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Партнер",
                "verbose_name_plural": "Партнеры",
                "db_table": "partner_db",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="src.partner",
                verbose_name="Партнер",
            ),
        ),
        migrations.CreateModel(
            name="FCMToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255, verbose_name="FCM-токен")),
                (
                    "device_id",
                    models.CharField(max_length=255, verbose_name="ID устройства"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_tokens",
                        to="src.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_tokens",
                        to="src.partner",
                        verbose_name="Партнер",
                    ),
                ),
            ],
            options={
                "verbose_name": "FCM-токен",
                "verbose_name_plural": "FCM-токены",
                "db_table": "fcmtoken_db",
            },
        ),
        migrations.CreateModel(
            name="PartnerService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verify_status",
                    models.CharField(
                        choices=[
                            ("on_confirmation", "Ожидает"),
                            ("confirmed", "Подтверждена"),
                            ("rejected", "Отклонена"),
                        ],
                        default="on_confirmation",
                        max_length=50,
                        verbose_name="Верификация услуги",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="src.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга партнера",
                "verbose_name_plural": "Услуги партнера",
                "db_table": "partner_service_db",
            },
        ),
        migrations.CreateModel(
            name="PartnerServiceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="src.option",
                        verbose_name="Опция",
                    ),
                ),
                (
                    "partner_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="src.partnerservice",
                        verbose_name="Услуга партнера с верификацией",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опция c услугой партнера",
                "verbose_name_plural": "Опции с услугами партнера",
                "db_table": "partner_service_option_db",
            },
        ),
        migrations.AddField(
            model_name="partnerservice",
            name="options",
            field=models.ManyToManyField(
                related_name="services",
                through="src.PartnerServiceOption",
                to="src.option",
                verbose_name="Опции партнерской услуги",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Текст отзыва",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата, время создания отзыва"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="src.client",
                        verbose_name="Клиент, оставивший отзыв",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="src.partner",
                        verbose_name="Партнер, о котором оставили отзыв",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "db_table": "review_db",
            },
        ),
        migrations.AddField(
            model_name="partnerservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="src.service"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="src.service",
                verbose_name="Услуга",
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="options",
                to="src.service",
                verbose_name="Услуга",
            ),
        ),
        migrations.CreateModel(
            name="Technic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(max_length=100, verbose_name="Марка автомобиля"),
                ),
                (
                    "car_model",
                    models.CharField(max_length=100, verbose_name="Модель автомобиля"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technics",
                        to="src.client",
                        verbose_name="Владелец автомобиля",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technics",
                        to="src.techniccategory",
                        verbose_name="Категория автомобиля",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автомобиль",
                "verbose_name_plural": "Автомобили",
                "db_table": "technic_db",
            },
        ),
        migrations.AddField(
            model_name="partnerservice",
            name="technic_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="src.techniccategory",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="technic_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="src.techniccategory",
                verbose_name="Категория техники",
            ),
        ),
        migrations.CreateModel(
            name="TinkoffTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(max_length=100, verbose_name="ID платежа"),
                ),
                (
                    "payment_url",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Url платежа"
                    ),
                ),
                (
                    "payment_token",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Token платежа"
                    ),
                ),
                (
                    "payment_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ответ платежной системы"
                    ),
                ),
                (
                    "webhook_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ответ по web hook"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "payment_artifact",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="url/token платежа",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Номер заказа транзакции",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Размер платежа",
                    ),
                ),
                (
                    "balance_type",
                    models.CharField(
                        choices=[
                            ("deposit_balance", "Депозитный баланс"),
                            ("commission_balance", "Комиссионный баланс"),
                        ],
                        max_length=100,
                        verbose_name="Тип баланса",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "В процессе исполнения"),
                            ("REJECTED", "Платеж отклонен"),
                            ("CONFIRMED", "Успешный одностадийный платеж"),
                            ("AUTHORIZED", "Успешный двухстадийный платеж"),
                        ],
                        default="IN_PROGRESS",
                        max_length=100,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="src.partner",
                        verbose_name="Партнер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция Tinkoff",
                "verbose_name_plural": "Транзакции Tinkoff",
                "db_table": "tinkoff_transaction_db",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="WorkingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название зоны"
                    ),
                ),
                (
                    "area_coordinates",
                    models.JSONField(default=list, verbose_name="Координаты зоны"),
                ),
                (
                    "departure_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Цена доставки",
                    ),
                ),
                (
                    "location_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("in_city", "В пределах города"),
                            ("out_city", "За пределами города"),
                        ],
                        null=True,
                        verbose_name="Статус зоны",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="working_zones",
                        to="src.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рабочая зона",
                "verbose_name_plural": "Рабочие зоны",
                "db_table": "working_zone_db",
            },
        ),
        migrations.AddConstraint(
            model_name="orderoption",
            constraint=models.UniqueConstraint(
                fields=("option", "order"),
                name="unique option of order",
                violation_error_message="Такая опция уже есть",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerserviceoption",
            constraint=models.UniqueConstraint(
                fields=("option", "partner_service"),
                name="unique option of partner service",
                violation_error_message="Такая опция уже есть",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerservice",
            constraint=models.UniqueConstraint(
                fields=("service", "partner", "technic_category"),
                name="unique service of partner",
                violation_error_message="Услуга уже существует",
            ),
        ),
    ]
