# Generated by Django 5.0.3 on 2024-11-22 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarBrandList",
            fields=[
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название бренда"),
                ),
                (
                    "cyrillic_title",
                    models.CharField(
                        max_length=150, verbose_name="Название бренда на кириллице"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "Список брендов",
                "verbose_name_plural": "Список брендов",
                "db_table": "car_brand_list_db",
            },
        ),
        migrations.AddField(
            model_name="partner",
            name="driver_licence",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/driver_licences/2024-11-22 10:59:54",
                verbose_name="Водительские права партнера",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="commission_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="Комиссионный баланс",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/2024-11-22 10:59:54",
                verbose_name="Фото партнера",
            ),
        ),
        migrations.CreateModel(
            name="CarModelList",
            fields=[
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название бренда"),
                ),
                (
                    "cyrillic_title",
                    models.CharField(
                        max_length=150, verbose_name="Название бренда на кириллице"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="models",
                        to="src.carbrandlist",
                        verbose_name="Бренд автомобиля",
                    ),
                ),
            ],
            options={
                "verbose_name": "Список брендов",
                "verbose_name_plural": "Список брендов",
                "db_table": "car_model_list_db",
            },
        ),
    ]
