# Generated by Django 5.0.3 on 2024-11-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0002_carbrandlist_partner_driver_licence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="driver_licence",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/driver_licences/2024-11-29 16:22:11",
                verbose_name="Водительские права партнера",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/2024-11-29 16:22:11",
                verbose_name="Фото партнера",
            ),
        ),
    ]
