# Generated by Django 5.0.3 on 2024-12-03 08:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0003_alter_partner_driver_licence_alter_partner_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="driver_licence",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/driver_licences/2024-12-03 11:57:11",
                verbose_name="Водительские права партнера",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/2024-12-03 11:57:11",
                verbose_name="Фото партнера",
            ),
        ),
        migrations.AlterField(
            model_name="workingzone",
            name="departure_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Цена доставки",
            ),
        ),
    ]
