# Generated by Django 5.0.3 on 2024-12-18 08:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0004_alter_partner_driver_licence_alter_partner_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="driver_licence",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/driver_licences/2024-12-18 11:40:28",
                verbose_name="Водительские права партнера",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/2024-12-18 11:40:28",
                verbose_name="Фото партнера",
            ),
        ),
        migrations.AlterField(
            model_name="tinkofftransaction",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tinkoff_transactions",
                to="src.partner",
                verbose_name="Партнер",
            ),
        ),
        migrations.CreateModel(
            name="CloudPaymentsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(max_length=100, verbose_name="ID платежа"),
                ),
                (
                    "payment_url",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Url платежа"
                    ),
                ),
                (
                    "payment_token",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Token платежа"
                    ),
                ),
                (
                    "payment_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ответ платежной системы"
                    ),
                ),
                (
                    "webhook_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ответ по web hook"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "payment_artifact",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="url/token платежа",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Номер заказа транзакции",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Размер платежа",
                    ),
                ),
                (
                    "balance_type",
                    models.CharField(
                        choices=[
                            ("deposit_balance", "Депозитный баланс"),
                            ("commission_balance", "Комиссионный баланс"),
                        ],
                        max_length=100,
                        verbose_name="Тип баланса",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Created", "Создан"),
                            ("Cancelled", "Отменен"),
                            ("Completed", "Успешный одностадийный платеж"),
                            ("Authorized", "Успешный двухстадийный платеж"),
                        ],
                        default="Created",
                        max_length=100,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cloud_payments_transactions",
                        to="src.partner",
                        verbose_name="Партнер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция CloudPayments",
                "verbose_name_plural": "Транзакции CloudPayments",
                "db_table": "cloud_payments_transaction_db",
                "ordering": ["-pk"],
            },
        ),
    ]
