# Generated by Django 5.0.3 on 2024-12-27 13:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0005_alter_partner_driver_licence_alter_partner_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderconditions",
            name="additional_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="driver_licence",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/driver_licences/2024-12-27 16:18:29",
                verbose_name="Водительские права партнера",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/2024-12-27 16:18:29",
                verbose_name="Фото партнера",
            ),
        ),
    ]
