# Generated by Django 5.0.3 on 2025-01-07 07:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0006_orderconditions_additional_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optionprice",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="driver_licence",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/driver_licences/2025-01-07 10:22:38",
                verbose_name="Водительские права партнера",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/2025-01-07 10:22:38",
                verbose_name="Фото партнера",
            ),
        ),
    ]
