# Generated by Django 5.0.3 on 2025-01-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0007_alter_optionprice_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partner",
            name="last_shift_date",
        ),
        migrations.AlterField(
            model_name="partner",
            name="driver_licence",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/driver_licences/2025-01-23 16:30:15",
                verbose_name="Водительские права партнера",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/2025-01-23 16:30:15",
                verbose_name="Фото партнера",
            ),
        ),
    ]
