# Generated by Django 5.0.3 on 2025-01-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0008_remove_partner_last_shift_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileAppVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ios_partner",
                    models.TextField(
                        max_length=100,
                        verbose_name="Версия iOS партнерского приложения",
                    ),
                ),
                (
                    "android_partner",
                    models.TextField(
                        max_length=100,
                        verbose_name="Версия Android партнерского приложения",
                    ),
                ),
                (
                    "ios_client",
                    models.TextField(
                        max_length=100, verbose_name="Версия iOS клиентского приложения"
                    ),
                ),
                (
                    "android_client",
                    models.TextField(
                        max_length=100,
                        verbose_name="Версия Android клиентского приложения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версии мобильных приложений",
                "verbose_name_plural": "Версии мобильных приложений",
                "db_table": "mobile_app_versions_db",
            },
        ),
        migrations.AlterField(
            model_name="partner",
            name="driver_licence",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/driver_licences/2025-01-30 12:06:09",
                verbose_name="Водительские права партнера",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/2025-01-30 12:06:09",
                verbose_name="Фото партнера",
            ),
        ),
    ]
