# Generated by Django 5.0.3 on 2025-02-07 12:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0009_mobileappversion_alter_partner_driver_licence_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommissionPercent",
        ),
        migrations.AddField(
            model_name="partner",
            name="commission_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Процент комиссии",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="driver_licence",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/driver_licences/2025-02-07 15:44:40",
                verbose_name="Водительские права партнера",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/2025-02-07 15:44:40",
                verbose_name="Фото партнера",
            ),
        ),
    ]
