# Generated by Django 5.0.3 on 2025-02-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0010_delete_commissionpercent_partner_commission_percent_and_more"),
    ]

    operations = []
