# Generated by Django 5.0.3 on 2025-02-13 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0011_auto_20250213_1637"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderconditions",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_conditions",
                to="src.city",
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="driver_licence",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/driver_licences/2025-02-13 16:38:44",
                verbose_name="Водительские права партнера",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/2025-02-13 16:38:44",
                verbose_name="Фото партнера",
            ),
        ),
    ]
