# Generated by Django 5.0.3 on 2025-03-19 09:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0012_orderconditions_city_alter_partner_driver_licence_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderconditions",
            name="city",
        ),
        migrations.AddField(
            model_name="orderconditions",
            name="option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_conditions",
                to="src.optionprice",
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="carbrandlist",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="carmodellist",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="src.carbrandlist",
                verbose_name="Бренд автомобиля",
            ),
        ),
        migrations.AlterField(
            model_name="carmodellist",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="orderconditions",
            name="additional_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="driver_licence",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/driver_licences/2025-03-19 12:17:59",
                verbose_name="Водительские права партнера",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/2025-03-19 12:17:59",
                verbose_name="Фото партнера",
            ),
        ),
    ]
