# Generated by Django 5.0.3 on 2025-06-25 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0013_remove_orderconditions_city_orderconditions_option_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="role",
            field=models.CharField(
                choices=[("super_admin", "Суперадмин"), ("operator", "Оператор")],
                default="operator",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="orderconditions",
            name="option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_conditions",
                to="src.optionprice",
                verbose_name="Опция",
            ),
        ),
        migrations.AlterField(
            model_name="orderoption",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="src.option",
                verbose_name="Опция",
            ),
        ),
        migrations.AlterField(
            model_name="orderoption",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="src.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="driver_licence",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/driver_licences/2025-06-25 14:57:51",
                verbose_name="Водительские права партнера",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/2025-06-25 14:57:51",
                verbose_name="Фото партнера",
            ),
        ),
    ]
