# Generated by Django 5.0.3 on 2025-09-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0014_admin_role_alter_orderconditions_option_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="driver_licence",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/driver_licences/2025-09-24 10:06:58",
                verbose_name="Водительские права партнера",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/2025-09-24 10:06:58",
                verbose_name="Фото партнера",
            ),
        ),
    ]
