# Generated by Django 5.0.3 on 2025-12-26 12:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0015_alter_partner_driver_licence_alter_partner_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="change_history",
            field=models.JSONField(
                blank=True,
                default=dict,
                null=True,
                verbose_name="История изменений опций",
            ),
        ),
        migrations.AddField(
            model_name="orderoption",
            name="quantity",
            field=models.SmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Минимальное количество: 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, message="Максимальное количество: 10"
                    ),
                ],
                verbose_name="Количество",
            ),
        ),
        migrations.AddField(
            model_name="workingzone",
            name="fuel_delivery_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Цена доставки топлива",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="driver_licence",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/driver_licences/2025-12-26 15:04:36",
                verbose_name="Водительские права партнера",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/partners/2025-12-26 15:04:36",
                verbose_name="Фото партнера",
            ),
        ),
        migrations.AddConstraint(
            model_name="optionprice",
            constraint=models.UniqueConstraint(
                fields=("option", "city", "technic_category"),
                name="unique option price",
                violation_error_message="Цена для данной опции в этом городе и категории техники уже существует",
            ),
        ),
    ]
