FROM python:3.11

ENV PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  POETRY_VERSION=1.4.0

RUN apt-get update && apt-get install -y python3-venv python3-setuptools
RUN pip install "poetry==$POETRY_VERSION"

WORKDIR /911
COPY poetry.lock pyproject.toml /911/

RUN poetry config installer.max-workers 10
RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

COPY . /911
RUN chmod -R 0777 /911

RUN adduser --disabled-password docker-admin
USER docker-admin


