# Generated by Django 5.0.3 on 2025-12-26 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("client", "Клиент"),
                            ("partner", "Партнер"),
                            ("both", "Оба"),
                        ],
                        max_length=20,
                        verbose_name="Целевая аудитория",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "icon_name",
                    models.CharField(max_length=50, verbose_name="Название иконки"),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
            ],
            options={
                "verbose_name": "Преимущество",
                "verbose_name_plural": "Преимущества",
                "db_table": "advantage",
                "ordering": ["display_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["target_audience", "is_active"],
                        name="advantage_target__7d98ab_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AppLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android")],
                        max_length=20,
                        verbose_name="Платформа",
                    ),
                ),
                (
                    "app_type",
                    models.CharField(
                        choices=[("client", "Клиент"), ("partner", "Партнер")],
                        max_length=20,
                        verbose_name="Тип приложения",
                    ),
                ),
                (
                    "store_url",
                    models.CharField(max_length=255, verbose_name="URL в магазине"),
                ),
                (
                    "qr_code_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="URL QR-кода"
                    ),
                ),
                (
                    "version",
                    models.CharField(blank=True, max_length=20, verbose_name="Версия"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Ссылка на приложение",
                "verbose_name_plural": "Ссылки на приложения",
                "db_table": "app_link",
                "unique_together": {("platform", "app_type")},
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название города"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="URL slug"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
                "db_table": "city",
                "ordering": ["display_order", "title"],
                "indexes": [
                    models.Index(fields=["slug"], name="city_slug_aeafd3_idx"),
                    models.Index(
                        fields=["is_active", "display_order"],
                        name="city_is_acti_d62c7c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CityContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(max_length=255, verbose_name="Meta Title"),
                ),
                ("meta_description", models.TextField(verbose_name="Meta Description")),
                (
                    "h1_title",
                    models.CharField(max_length=255, verbose_name="Заголовок H1"),
                ),
                (
                    "short_description",
                    models.TextField(verbose_name="Краткое описание"),
                ),
                (
                    "full_description",
                    models.TextField(verbose_name="Полное описание (HTML)"),
                ),
                (
                    "advantages_html",
                    models.TextField(blank=True, verbose_name="Преимущества (HTML)"),
                ),
                (
                    "partner_count",
                    models.IntegerField(default=0, verbose_name="Количество партнеров"),
                ),
                (
                    "avg_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        verbose_name="Средний рейтинг",
                    ),
                ),
                (
                    "review_count",
                    models.IntegerField(default=0, verbose_name="Количество отзывов"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "city",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="website_api.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контент города",
                "verbose_name_plural": "Контент городов",
                "db_table": "city_content",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        help_text="phone, email, telegram, whatsapp, vk, instagram и т.д.",
                        max_length=50,
                        verbose_name="Тип контакта",
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Значение")),
                ("label", models.CharField(max_length=255, verbose_name="Метка")),
                (
                    "icon_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Название иконки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "db_table": "contact",
                "ordering": ["display_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["contact_type", "is_active"],
                        name="contact_contact_6106d0_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Ключ метрики"
                    ),
                ),
                ("value", models.CharField(max_length=100, verbose_name="Значение")),
                (
                    "display_label",
                    models.CharField(max_length=255, verbose_name="Отображаемая метка"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "metric_type",
                    models.CharField(
                        help_text="platform, partner, client, city, service",
                        max_length=50,
                        verbose_name="Тип метрики",
                    ),
                ),
                (
                    "is_visible_on_site",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на сайте"
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Название иконки"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
            ],
            options={
                "verbose_name": "Метрика",
                "verbose_name_plural": "Метрики",
                "db_table": "metric",
                "ordering": ["display_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["metric_key"], name="metric_metric__365382_idx"
                    ),
                    models.Index(
                        fields=["is_visible_on_site", "display_order"],
                        name="metric_is_visi_bec9e2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название услуги"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="URL slug"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "db_table": "service",
                "ordering": ["display_order", "title"],
                "indexes": [
                    models.Index(fields=["slug"], name="service_slug_41154d_idx"),
                    models.Index(
                        fields=["is_active"], name="service_is_acti_dc9003_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название опции"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="website_api.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опция",
                "verbose_name_plural": "Опции",
                "db_table": "option",
            },
        ),
        migrations.CreateModel(
            name="TechnicCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название категории"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technic_categories",
                        to="website_api.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория техники",
                "verbose_name_plural": "Категории техники",
                "db_table": "technic_category",
            },
        ),
        migrations.CreateModel(
            name="SeoMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        help_text="home, city, service, city_service, about, contacts",
                        max_length=50,
                        verbose_name="Тип страницы",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("meta_description", models.TextField(verbose_name="Meta Description")),
                (
                    "meta_keywords",
                    models.TextField(blank=True, verbose_name="Meta Keywords"),
                ),
                (
                    "h1_title",
                    models.CharField(max_length=255, verbose_name="H1 заголовок"),
                ),
                (
                    "full_slug",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Полный slug"
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="OG Title"
                    ),
                ),
                (
                    "og_description",
                    models.TextField(blank=True, verbose_name="OG Description"),
                ),
                (
                    "og_image_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="OG Image URL"
                    ),
                ),
                (
                    "schema_json",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Schema.org JSON"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_metas",
                        to="website_api.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_metas",
                        to="website_api.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO метаданные",
                "verbose_name_plural": "SEO метаданные",
                "db_table": "seo_meta",
                "indexes": [
                    models.Index(
                        fields=["full_slug"], name="seo_meta_full_sl_bb2a09_idx"
                    ),
                    models.Index(
                        fields=["page_type", "is_active"],
                        name="seo_meta_page_ty_276096_idx",
                    ),
                ],
                "unique_together": {("page_type", "city", "service")},
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "source_page",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Страница источник"
                    ),
                ),
                (
                    "utm_source",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="UTM Source"
                    ),
                ),
                (
                    "utm_medium",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="UTM Medium"
                    ),
                ),
                (
                    "utm_campaign",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="UTM Campaign"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("processing", "В обработке"),
                            ("converted", "Конвертирована"),
                            ("rejected", "Отклонена"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата обработки"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="website_api.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="website_api.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "db_table": "lead",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="lead_status_f118bd_idx"
                    ),
                    models.Index(
                        fields=["city", "-created_at"], name="lead_city_id_5de8cc_idx"
                    ),
                    models.Index(
                        fields=["service", "-created_at"],
                        name="lead_service_c20355_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(max_length=255, verbose_name="Meta Title"),
                ),
                ("meta_description", models.TextField(verbose_name="Meta Description")),
                (
                    "h1_title",
                    models.CharField(max_length=255, verbose_name="Заголовок H1"),
                ),
                ("description", models.TextField(verbose_name="Описание (HTML)")),
                (
                    "how_it_works_html",
                    models.TextField(
                        blank=True, verbose_name="Как это работает (HTML)"
                    ),
                ),
                (
                    "benefits_html",
                    models.TextField(blank=True, verbose_name="Преимущества (HTML)"),
                ),
                (
                    "icon_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="URL иконки"
                    ),
                ),
                (
                    "cover_image_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="URL обложки"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL для общего описания услуги",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_contents",
                        to="website_api.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="website_api.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контент услуги",
                "verbose_name_plural": "Контент услуг",
                "db_table": "service_content",
                "unique_together": {("service", "city")},
            },
        ),
        migrations.CreateModel(
            name="OptionPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Цена"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_prices",
                        to="website_api.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="website_api.option",
                        verbose_name="Опция",
                    ),
                ),
                (
                    "technic_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="option_prices",
                        to="website_api.techniccategory",
                        verbose_name="Категория техники",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цена опции",
                "verbose_name_plural": "Цены опций",
                "db_table": "option_price",
                "indexes": [
                    models.Index(
                        fields=["option", "city"], name="option_pric_option__f726c9_idx"
                    )
                ],
                "unique_together": {("option", "city", "technic_category")},
            },
        ),
    ]
