# Generated by Django 5.0.3 on 2025-12-30 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParameterType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Уникальный код, например: tire_radius, oil_type, fuel_type",
                        max_length=50,
                        unique=True,
                        verbose_name="Код параметра",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Отображаемое название, например: 'Радиус шины', 'Тип масла'",
                        max_length=150,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Подсказка для пользователя при выборе",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Тип параметра",
                "verbose_name_plural": "Типы параметров",
                "db_table": "parameter_type",
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.AddField(
            model_name="option",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Подробное описание опции для пользователя",
                verbose_name="Описание",
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="has_parameters",
            field=models.BooleanField(
                default=False,
                help_text="Если True, цена зависит от выбранных параметров. Если False, используется фиксированная цена из OptionPrice.",
                verbose_name="Есть параметры",
            ),
        ),
        migrations.CreateModel(
            name="ParameterValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Техническое значение, например: R15, synthetic_5w40",
                        max_length=100,
                        verbose_name="Значение",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Название для пользователя, например: 'R15', 'Синтетика 5W-40'",
                        max_length=150,
                        verbose_name="Отображаемое название",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "parameter_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="website_api.parametertype",
                        verbose_name="Тип параметра",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение параметра",
                "verbose_name_plural": "Значения параметров",
                "db_table": "parameter_value",
                "ordering": ["parameter_type", "sort_order"],
                "unique_together": {("parameter_type", "value")},
            },
        ),
        migrations.CreateModel(
            name="PriceChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("OPTION_PRICE", "Цена опции"),
                            ("PARAMETER_PRICE", "Цена параметра"),
                            ("DELIVERY_ZONE", "Зона доставки"),
                        ],
                        max_length=50,
                        verbose_name="Тип сущности",
                    ),
                ),
                ("entity_id", models.IntegerField(verbose_name="ID сущности")),
                (
                    "entity_description",
                    models.CharField(
                        help_text="Читаемое описание, что изменилось",
                        max_length=255,
                        verbose_name="Описание сущности",
                    ),
                ),
                (
                    "old_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Старое значение",
                    ),
                ),
                (
                    "new_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Новое значение"
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения"
                    ),
                ),
                (
                    "changed_by",
                    models.CharField(
                        help_text="Email или имя пользователя",
                        max_length=150,
                        verbose_name="Изменил",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="Причина изменения"),
                ),
            ],
            options={
                "verbose_name": "Лог изменения цены",
                "verbose_name_plural": "Логи изменений цен",
                "db_table": "price_change_log",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="price_chang_entity__908e6a_idx",
                    ),
                    models.Index(
                        fields=["changed_at"], name="price_chang_changed_0b64c7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zone_name",
                    models.CharField(
                        help_text="Например: 'В городе', 'За городом', 'Пригород'",
                        max_length=100,
                        verbose_name="Название зоны",
                    ),
                ),
                (
                    "location_status",
                    models.CharField(
                        choices=[("in_city", "В городе"), ("out_city", "За городом")],
                        max_length=20,
                        verbose_name="Статус зоны",
                    ),
                ),
                (
                    "delivery_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена выезда"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_zones",
                        to="website_api.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зона доставки",
                "verbose_name_plural": "Зоны доставки",
                "db_table": "delivery_zone",
                "unique_together": {("city", "location_status")},
            },
        ),
        migrations.CreateModel(
            name="OptionParameterType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Если True, пользователь обязан выбрать значение этого параметра",
                        verbose_name="Обязательный",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter_types",
                        to="website_api.option",
                        verbose_name="Опция",
                    ),
                ),
                (
                    "parameter_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_links",
                        to="website_api.parametertype",
                        verbose_name="Тип параметра",
                    ),
                ),
            ],
            options={
                "verbose_name": "Параметр опции",
                "verbose_name_plural": "Параметры опций",
                "db_table": "option_parameter_type",
                "unique_together": {("option", "parameter_type")},
            },
        ),
        migrations.CreateModel(
            name="ParameterPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_modifier",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Надбавка к базовой цене опции",
                        max_digits=10,
                        verbose_name="Модификатор цены",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter_prices",
                        to="website_api.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter_prices",
                        to="website_api.option",
                        verbose_name="Опция",
                    ),
                ),
                (
                    "technic_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Если цена зависит от категории техники",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parameter_prices",
                        to="website_api.techniccategory",
                        verbose_name="Категория техники",
                    ),
                ),
                (
                    "parameter_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="website_api.parametervalue",
                        verbose_name="Значение параметра",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цена параметра",
                "verbose_name_plural": "Цены параметров",
                "db_table": "parameter_price",
                "indexes": [
                    models.Index(
                        fields=["option", "city"], name="parameter_p_option__eaec52_idx"
                    ),
                    models.Index(
                        fields=["parameter_value", "city"],
                        name="parameter_p_paramet_37e3ca_idx",
                    ),
                ],
                "unique_together": {
                    ("option", "parameter_value", "city", "technic_category")
                },
            },
        ),
    ]
