# Generated by Django 5.0.3 on 2025-12-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_api', '0002_pricing_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniccategory',
            name='service',
        ),
        migrations.AddField(
            model_name='techniccategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly идентификатор', max_length=100, verbose_name='Slug'),
        ),
    ]

