# Generated by Django 5.0.3 on 2025-12-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_api', '0007_add_short_description_to_servicecontent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='lead_lead_ty_826d52_idx',
            old_name='lead_lead_ty_123abc_idx',
        ),
        migrations.AlterField(
            model_name='servicecontent',
            name='description',
            field=models.TextField(verbose_name='Полное описание (HTML)'),
        ),
    ]

