# Generated by Django 5.0.3 on 2024-11-14 16:08

import django.db.models.deletion
import users.services.validation.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        validators=[
                            users.services.validation.model_validators.validate_charfield_for_letters
                        ],
                        verbose_name="Номер телефона",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("is_admin", models.BooleanField(default=False, verbose_name="Админ")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False, verbose_name="Суперпользователь"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Персонал"),
                ),
                (
                    "admin",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_user",
                        to="src.admin",
                        verbose_name="Админ",
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_user",
                        to="src.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "partner",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_user",
                        to="src.partner",
                        verbose_name="Партнер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "indexes": [
                    models.Index(fields=["-phone"], name="users_custo_phone_847921_idx")
                ],
            },
        ),
    ]
